<a href="https://colab.research.google.com/github/jpskycak/aihigh/blob/master/intro-to-ai/codingBootcamp_listsDictionariesArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Setup

In order to run the notebook,

1. sign into your Google account (top-right) and
2. make a copy of the notebook in your Google Drive by pressing the <img src="https://i.imgur.com/chlzY9P.png" alt="Drawing" width="100"/> button in the upper-left menu.

---

#Data Structures

When programming, we often work with many related pieces of data. To be organized and efficient, we store them within a single variable called a <b>data structure.</b> This way, we can efficiently perform operations on the data structure as a whole rather than having to operate on each piece of data as a separate variable.

We will primarily be using 3 types of data structures: lists, dictionaries, and arrays.
<ul>
<li><b>Lists</b> store pieces of data in a sequence, so that data can be referenced by its index in the list.</li>
  <li><b>Dictionaries</b> store pieces of data under labels called <i>keys</i>, so that data can be referenced its key in the dictionary.</li>
<li><b>Arrays</b> store pieces of data in matrices and higher-dimensional matrices called <i>tensors</i>, so that data can be referenced by its index in the matrix or tensor.</li>
</ul>

---

##Lists

A list is defined by enclosing a sequence of data within brackets.


In [0]:
mixed_list = [5,-9,3.14,'a','b','c',True,False]
mixed_list

[5, -9, 3.14, 'a', 'b', 'c', True, False]

Two lists can be concatenated into a single list by adding them together.

In [0]:
[1,2,3]+['a','b','c']

[1, 2, 3, 'a', 'b', 'c']

---

### Exercise 1

Add the following lists in some order to create the list `['a','c',5,1.2,True]`.

In [0]:
list1 = [True]
list2 = ['a','c']
list3 = [5,1.2]
list1+list2+list3 # change the order of addition to create the list ['a','c',5,1.2,True]

[True, 'a', 'c', 5, 1.2]

---

Referencing items in lists is very similar to picking out characters from strings -- we can simply use the index of the item. (Really, a string is just a list of characters.)

Remember, the index just counts how many items are before our desired item -- so the first item has an index of 0, the second item has an index of 1, the third item has an index of 2, and so on.

In [0]:
mixed_list = [5,-9,3.14,'a','b','c',True,False]
mixed_list[0]

5

In [0]:
mixed_list = [5,-9,3.14,'a','b','c',True,False]
mixed_list[3]

'a'

---

### Exercise 2

Reference the item `'c'` in `mixed_list` using its index in the list.

In [0]:
mixed_list = [5,-9,3.14,'a','b','c',True,False]
mixed_list[1] # change the index to reference the item 'c'

-9

---

Just as substrings can be picked out of strings, sublists can be picked out of sublists by using two indices and a colon.

Remember, the first index tells us where we should start picking out items, and the second index tells us where we should stop picking out items. (The item located at the second index is not included in the sublist.)

In [0]:
mixed_list = [5,-9,3.14,'a','b','c',True,False]
mixed_list[2:4]

[3.14, 'a']

---

### Exercise 3

Pick out the sublist `['a','b','c']` from `mixed_list` by using two indices and a colon.

In [0]:
mixed_list = [5,-9,3.14,'a','b','c',True,False]
mixed_list[2:4] # change the two indices so that the resulting sublist is ['a','b','c']

[3.14, 'a']

---

There are various functions and methods that can be used to process lists.

For example, the `len()` function tells us how many items are in a list.

In [0]:
mixed_list = [5,-9,3.14,'a','b','c',True,False]
len(mixed_list)

8

Likewise, the `.insert(i,x)` method inserts the item `x` into the list so that it occupies index `i`.

In [0]:
alphabet_missing_c = ['a','b','d','e']
alphabet_missing_c.insert(2,'c')
alphabet_missing_c

['a', 'b', 'c', 'd', 'e']

There are many functions and methods that can be applied to lists. As such, we will not go through all of them.

However, it is important to know how to find a function or method when you need it. You can usually find them by searching Google.

---

### Exercise 4

Use functions or methods to perform the desired operations on the following lists.

In [0]:
counting_up = [1,2,3,4,5] # reverse the list so that it is counting down: [5,4,3,2,1]

In [0]:
has_lots_of_Es = ['a','b','e','c','d','e','e','f','e','e'] # count how many items in the list have the value 'e'

---

##Dictionaries

A dictionary is defined by enclosing a sequence of `key:value` pairs within braces.


In [0]:
my_dict = {'Leroy':5, 'Amy':2, 'Pete':True, 'Carly':'hi'}
my_dict

{'Amy': 2, 'Carly': 'hi', 'Leroy': 5, 'Pete': True}

To reference an item in a dictionary, we can simply use the key of that item.

In [0]:
my_dict = {'Leroy':5, 'Amy':2, 'Pete':True, 'Carly':'hi'}
my_dict['Amy']

2

---

### Exercise 5

Reference the item in `my_dict` corresponding to the key `'Pete'`.

In [0]:
my_dict = {'Leroy':5, 'Amy':2, 'Pete':True, 'Carly':'hi'}
my_dict['Amy'] # change the key 'Amy' to the key 'Pete'

2

---

To add a new item to a dictionary, we can reference a new key and assign a value to it just like we would assign a new value to a variable.

In [0]:
my_dict = {'Leroy':5, 'Amy':2, 'Pete':True, 'Carly':'hi'}
my_dict['Jaspreet'] = 9 # create a key 'Jaspreet' with value 9
my_dict # dictionary now contains a new key:value pair!

{'Amy': 2, 'Carly': 'hi', 'Jaspreet': 9, 'Leroy': 5, 'Pete': True}

We can use the same technique to change the value of an existing key in a dictionary.

In [0]:
my_dict = {'Leroy':5, 'Amy':2, 'Pete':True, 'Carly':'hi'}
my_dict['Pete'] = False # re-assign the key 'Pete' to the value False
my_dict # dictionary has been modified

{'Amy': 2, 'Carly': 'hi', 'Leroy': 5, 'Pete': False}

---

### Exercise 6

Add a key-value pair `'e':3` to `my_dict`, and change the value of the key `'a'` to 4.

In [0]:
my_dict = {'a':8, 'b':6, 's':5, 'i':1}
# insert some code here to add a key-value pair 'e':3
# insert some code here to change the value of the key 'a' to 4
my_dict

{'a': 8, 'b': 6, 'i': 1, 's': 5}

---

There are various functions and methods that can be used to process dictionaries.

For example, the `len()` function tells us how many `key:value` pairs are in the dictionary.

In [0]:
my_dict = {'Leroy':5, 'Amy':2, 'Pete':True, 'Carly':'hi'}
len(my_dict)

4

Likewise, the `.pop(keyname)` method allows us to remove the `key:value` pair corresponding to the key `keyname`.

In [0]:
my_dict = {'Leroy':5, 'Amy':2, 'Pete':True, 'Carly':'hi'}
my_dict.pop('Pete') # remove Pete
my_dict # Pete is gone!

{'Amy': 2, 'Carly': 'hi', 'Leroy': 5}

---

##Arrays

To use arrays, we need to import the NumPy module which contains the code needed to create and manipulate arrays. We do this by adding `import numpy` at the top of our code.

Then, we can call `numpy.array(<list of lists>)` to create a matrix array.


In [0]:
import numpy
my_array = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

We can reference the entry in the <i>i</i>-th row and <i>j</i>-th column of the array using the notation `[i,j]`. Remember to start counting with 0.

In [0]:
import numpy
my_array = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
my_array[0,0]

1

In [0]:
import numpy
my_array = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
my_array[1,2]

6

---

### Exercise 7

Reference the entry in the bottom-left corner of the array (which is 7) using `[i,j]` notation.

In [0]:
import numpy
my_array = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
my_array[1,2] # change this [i,j] notation to reference the entry in the bottom-left corner (which is 7)

6

---

We can reference subarrays within arrays just like we reference sublists within lists.

In [0]:
import numpy
my_array = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
my_array[0:2,0:2] # gives the 2x2 square in the top-left corner

array([[1, 2],
       [4, 5]])

---

### Exercise 8

Reference the 2x2 square in the top-right corner of the array in the bottom-left corner of the array (which is $\begin{bmatrix} 2 & 3 \\ 5 & 6 \end{bmatrix}$) using subarray notation.

In [0]:
import numpy
my_array = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
my_array[0:2,0:2] # change the subarray notation to reference the 2x2 square in the top-right corner

array([[1, 2],
       [4, 5]])

---

Arrays of the same shape can be added and subtracted.

In [0]:
import numpy
A = numpy.array([[10,10],[20,20]])
B = numpy.array([[1,2],[3,4]])
A+B

array([[11, 12],
       [23, 24]])

In [0]:
import numpy
A = numpy.array([[10,10],[20,20]])
B = numpy.array([[1,2],[3,4]])
A-B

array([[ 9,  8],
       [17, 16]])

---

### Caution 1

Arrays of the same shape can also be multiplied and divided. But the multiplication and division is carried out separately in each component -- so array multiplication is not the same as the matrix multiplication procedure you may have learned in math class.

In [0]:
import numpy
A = numpy.array([[1,2],[3,4]])
B = numpy.array([[1,1],[2,2]])
A*B

array([[1, 2],
       [6, 8]])

In [0]:
import numpy
A = numpy.array([[1,2],[3,4]])
B = numpy.array([[1,1],[2,2]])
A/B

array([[1. , 2. ],
       [1.5, 2. ]])

---

Some seemingly improper array operations are allowed if there is a way to make intuitive sense of them.

For example, if a single number is added to an array, then the number is added to each entry of the array.

In [0]:
import numpy
A = numpy.array([[1,2],[3,4]])
A+10

array([[11, 12],
       [13, 14]])

Likewise, if a single row is added to a square array of the same length, then the row is added to each row of the square array.

In [0]:
import numpy
A = numpy.array([[1,2],[3,4]])
b = numpy.array([10,20])
A+b

array([[11, 22],
       [13, 24]])

---

### Exercise 9

Change array `B` so that `A+B` comes out to a matrix whose entries are all `10`.

In [0]:
import numpy
A = numpy.array([[1,2],[3,4]])
B = numpy.array([[1,1],[1,1]]) # change the entries here so that A+B has all entries equal to 10
A+B

array([[2, 3],
       [4, 5]])

---

There are various methods and attributes that can be used to process lists. 

(You can think of attributes as being the same as methods, but without parentheses.)

For example, the `.max()` method tells us the maximum entry in the array.

In [0]:
import numpy
A = numpy.array([[1,2],[3,4]])
A.max()

4

Also, the `.dot()` method allows us to compute a product with another array in the mathematical sense of matrix multiplication.

In [0]:
import numpy
A = numpy.array([[1,2],[3,4]])
b = numpy.array([[5],[6]])
A.dot(b)

array([[17],
       [39]])

Likewise, the `.shape` attribute tells us how many rows and columns an array has.

In [0]:
import numpy
A = numpy.array([[1,2],[3,4],[5,6]])
print('A =\n',A)
print('\n')
print('A.shape =',A.shape)

A =
 [[1 2]
 [3 4]
 [5 6]]


A.shape = (3, 2)


There are many methods that can be applied to arrays. As such, we will not go through all of them.

However, it is important to know how to find a method when you need it. You can usually find them by searching Google.

---

### Exercise 10

Use methods to perform the desired operations on the following arrays.

In [0]:
import numpy
A = numpy.array([[1,2],[3,4]])
A # apply a method to find the minimum entry in the array

array([[1, 2],
       [3, 4]])

In [0]:
import numpy
A = numpy.array([[1,2],[3,4]])
A # apply a method to sum all the entries in the array

array([[1, 2],
       [3, 4]])

---

We can also stack two 2x2 matrices to form a 2x2x2 cube of numbers, called a  3-dimensional tensor.

In [0]:
import numpy
bottom_layer = numpy.array([[1,2],[3,4]])
top_layer = numpy.array([[5,6],[7,8]])
cube = numpy.stack((bottom_layer,top_layer))

Indexing for a tensor is the same as indexing for a matrix -- except that the tensor has more dimensions.

When stacking matrices to form a tensor, the new "depth" dimension becomes the first dimension.

In [0]:
cube[0,0:2,0:2] # bottom layer

array([[1, 2],
       [3, 4]])

In [0]:
cube[1,0:2,0:2] # top layer

array([[5, 6],
       [7, 8]])

---

### Exercise 11

Adjust the indices referenced in the cube so that the resulting matrix cross-section is $\begin{bmatrix} 3 & 4 \\ 7 & 8 \end{bmatrix}$. (Hint: take a cross-section that cuts the cube along a different dimension.)

In [0]:
cube[0:2,0:2,0:2] # adjust these indices

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])