<a href="https://colab.research.google.com/github/jpskycak/aihigh/blob/master/intro-to-ai/codingBootcamp_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Solutions

## Getting Started in Colab

### Exercise 6

In [0]:
print('The second code cell has been executed.')

The second code cell has been executed.


### Exercise 7

In [0]:
#This code prints out the first digit of a number.
n=2**3*4 # The number is 2 to the power of 3, times 4.
print(str(n)[0]) # We print out the first digit of the number.
print('If this prints out, then the code ran successfully!')

3
If this prints out, then the code ran successfully!


## Strings, Ints, Floats, and Booleans

### Exercise 1

In [0]:
my_sentence = 'This is a sentence.'
print(my_sentence)

This is a sentence.


### Exercise 2

In [0]:
my_sentence = 'I have commandeered your sentence.'
print(my_sentence)

I have commandeered your sentence.


### Exercise 3

In [0]:
var1='dog'
var2='over'
var3='cat'
var4='the'
var5='jumped'
var6='The'
var7=' '
var8='.'
var6+var7+var1+var7+var5+var7+var2+var7+var4+var7+var3+var8

'The dog jumped over the cat.'

### Exercise 4

In [0]:
'My shoes have laces.'[3:13]

'shoes have'

### Exercise 5

In [0]:
'This should look like shouting.'.upper()

'THIS SHOULD LOOK LIKE SHOUTING.'

In [0]:
'         This should have no spaces at the beginning nor the end.             '.strip()

'This should have no spaces at the beginning nor the end.'

### Exercise 6

In [0]:
a=3
b=2.5
c=30*a-30*b
print(c)

15.0


### Exercise 7

In [0]:
is_normal = False
is_surprising = False
is_weird = True
is_normal or is_surprising or is_weird

True

### Exercise 8

In [0]:
'asdf98qoiuretkjld'.isalpha()

False

In [0]:
4.2.is_integer()

False

## Lists, Dictionaries, and Arrays

### Exercise 1

In [0]:
list1 = [True]
list2 = ['a','c']
list3 = [5,1.2]
list2+list3+list1

['a', 'c', 5, 1.2, True]

### Exercise 2

In [0]:
mixed_list = [5,-9,3.14,'a','b','c',True,False]
mixed_list[5]

'c'

### Exercise 3

In [1]:
mixed_list = [5,-9,3.14,'a','b','c',True,False]
mixed_list[3:6]

['a', 'b', 'c']

### Exercise 4

In [3]:
counting_up = [1,2,3,4,5]
counting_up.reverse()
counting_up

[5, 4, 3, 2, 1]

In [4]:
has_lots_of_Es = ['a','b','e','c','d','e','e','f','e','e']
has_lots_of_Es.count('e')

5

### Exercise 5

In [5]:
my_dict = {'Leroy':5, 'Amy':2, 'Pete':True, 'Carly':'hi'}
my_dict['Pete']

True

### Exercise 6

In [6]:
my_dict = {'a':8, 'b':6, 's':5, 'i':1}
my_dict['e'] = 3
my_dict['a'] = 4
my_dict

{'a': 4, 'b': 6, 'e': 3, 'i': 1, 's': 5}

### Exercise 7

In [7]:
import numpy
my_array = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
my_array[2,0]

7

### Exercise 8

In [8]:
import numpy
my_array = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
my_array[0:2,1:3]

array([[2, 3],
       [5, 6]])

### Exercise 9

In [9]:
import numpy
A = numpy.array([[1,2],[3,4]])
B = numpy.array([[9,8],[7,6]])
A+B

array([[10, 10],
       [10, 10]])

### Exercise 10

In [14]:
import numpy
A = numpy.array([[1,2],[3,4]])
A.min()

1

In [15]:
import numpy
A = numpy.array([[1,2],[3,4]])
A.sum()

10

### Exercise 11

In [13]:
import numpy
bottom_layer = numpy.array([[1,2],[3,4]])
top_layer = numpy.array([[5,6],[7,8]])
cube = numpy.stack((bottom_layer,top_layer))

cube[0:2,1,0:2]

array([[3, 4],
       [7, 8]])

## If, While, and For